### ISSUE TITLE
missing special characters in generated css files

### ISSUE THREAD

**Issue by alireza19330** [fgiannesini/LibSassGradlePlugin#7]
I have some special chars in my scss file. like "→" or "•"
But in the compiled css file, instead of all special chars, there is a "?"
Did I miss something in config or somewhere else?

**Comment by fgiannesini** [comment]
Hello,

I try to compile your chars:
-"•" works for me (maybe because i have `@charset "UTF-8";` on top of my scss file
-"→" displays a "?"

So, i try to update to last version of compiler (libsass 3.5.2 through jsass 5.7.0), same results.
I checked i write css files by using default charset, UTF-8.

As a result, i think your problem comes from original compiler libsass:
-you could open an issue on their github [https://github.com/sass/libsass](https://github.com/sass/libsass)
-you could try a workaround [http://nealchester.com/special-characters/](http://nealchester.com/special-characters/)

**Comment by alireza19330** [comment]
Hi,
I finally managed to resolve the problem, I add the setting below in my gradle.properties:

`org.gradle.jvmargs='-Dfile.encoding=UTF-8'`

it resolved my problem. and I changed your code to use UTF-8 instead of default charset and then the same result, it worked fine.

**Comment by fgiannesini** [comment]
Ok, thanks
